### ISSUE TITLE
Warning: dry runpanic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by penguinpee** [Frazew/rrdmerge#1]
I was in the need of merging RRD files after Munin misbehaved following a system restart. I gave _rrdmerge_ a try, but was faced with below error when running `rrdmerge -dry -a file_a.rrd -b file_b.rrd` (not the actual file names). 

```bash
Warning: dry runpanic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/scaleway/rrdmerge/internal/rrd.(*Rrd).Read(0x546000, 0x514260, 0xea4e0, 0x546000, 0x546000, 0x0, 0x0)
	/home/sandro/devel/rrdmerge/internal/rrd/rrd.go:40 +0xe4
github.com/scaleway/rrdmerge/internal/merger.loadRrd(0xbea966df, 0x42, 0x4000e0, 0x428a00, 0xa1040)
	/home/sandro/devel/rrdmerge/internal/merger/merger.go:180 +0xb8
github.com/scaleway/rrdmerge/internal/merger.merge(0xbea966df, 0x42, 0xbea96725, 0x44, 0x0, 0x0, 0x0, 0x0, 0x122d01)
	/home/sandro/devel/rrdmerge/internal/merger/merger.go:191 +0x34
github.com/scaleway/rrdmerge/internal/merger.(*MergeSpec).mergeFile(...)
	/home/sandro/devel/rrdmerge/internal/merger/merger.go:145
github.com/scaleway/rrdmerge/internal/merger.(*MergeSpec).DoMerge(0x440f88, 0xc0a4a971, 0x7d1270)
	/home/sandro/devel/rrdmerge/internal/merger/merger.go:76 +0x78
main.main()
	/home/sandro/devel/rrdmerge/cmd/rrdmerge/main.go:67 +0x588

**Comment by frazew** [comment]
Apparently the parsing of the RRD file failed and the DsCount would seem to have been incorrectly interpreted? Could you either:

- provide a XML dump of the RRD files (at least the headers)
- provide the raw RRD files themselves?
- or just debug with a quick `fmt.Printf` on the `this.Header.DsCount` value

Thanks!

**Comment by penguinpee** [comment]
Thanks for the quick response.

I can provide the files. Not sure how to carry out the debugging but I'll try to find out. Hints are welcome.

[rrd_files.zip](https://github.com/Frazew/rrdmerge/files/8952940/rrd_files.zip)

**Comment by frazew** [comment]
Ah, are the RRDs coming from a system running on a 32bit CPU? The RRD file format is architecture-dependent I believe

**Comment by penguinpee** [comment]
Yes. It's from a RaspberryPi using armv7l architecture to be precise.

**Comment by penguinpee** [comment]
I just added the `fmt.Printf(this.Header.DsCount)` to `rrd.go`:

```golang
$ make build
go build -tags rrdtool -o bin/rrdmerge ./cmd/rrdmerge
# github.com/scaleway/rrdmerge/internal/rrd
internal/rrd/rrd.go:42:27: cannot use this.Header.DsCount (type uint64) as type string in argument to fmt.Printf
```

Could I just use 32 bit integers instead (as a quick and dirty hack)?

**Comment by frazew** [comment]
I've just pushed what I believe to be a first step towards a fix for that. The file format has several changes because of being 32bit but the parser now seems to work as expected in that case. I am however not sure the rest of the logic works correctly, could you try with this new version? You can now compile the a 32bit variant (see the Makefile build target)

**Comment by penguinpee** [comment]
Thanks a lot. I tried it out. Build went fine as before. Dry run worked without issues, so I went ahead and merged two files. No warnings or errors were issued, but Munin is no longer able to graph the result it seems. It got stuck on the first run after the merge. I'll dig into that. But maybe the resulting file is not okay. It's attached.

[file_b.rrd.zip](https://github.com/Frazew/rrdmerge/files/8970933/file_b.rrd.zip)

**Comment by penguinpee** [comment]
I haven't been able to determine why Munin graphing chokes on the merged files, but it's definitely the merged files it chokes on. As soon as I moved them out of the way, munin-cgi-graph was going about its business as usual. In this case two RRDs were used for one graph.

I'll have a look at the XML dumps of the merged files, tomorrow, and compare them to unmerged files of a similar type to see if something jumps out.

**Comment by frazew** [comment]
I believe there could be an issue during the dumping indeed because of uint32 -> uint64 conversions that could mess things up when rrdtool restores from XML. I'll investigate on my side too, just need to get my hands on an armv7l device to make testing easier

**Comment by frazew** [comment]
Quick update: got a chance to test this on an armv7l device and I think I found the issue, just updated the parser accordingly and from what I can see, it seems to produce reasonable output. Hopefully you can confirm that :)

**Comment by penguinpee** [comment]
Yes, I can. :+1: I suppose it was rrdtool itself crashing that made munin-cgi-graph choke. When I tried to dump one of the previous merges it crashed with `Floating point exception (core dumped)`.

Excellent work! Thanks a lot. I guess this extends the audience of this tool.
